import { Component } from '@angular/core';

@Component({
  selector: 'app-attendence',
  templateUrl: './attendence.component.html',
  styleUrls: ['./attendence.component.scss']
})
export class AttendenceComponent {
  // Sample class options
  classes = ['Class 1', 'Class 2', 'Class 3', 'Class 4', 'Class 5', 'Class 6', 'Class 7', 'Class 8', 'Class 9', 'Class 10'];

  // Initially selected class and attendance data
  selectedClass = this.classes[0];
  selectedDate: string = '2024-12-30'; // You can adjust this to the current date or another logic for date.

  // Sample student data (this could be replaced with a real API call)
  allAttendance = [

    { name: 'Ishita Islam', class: 'Class 1', roll: 3, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Rina Chowdhury', class: 'Class 1', roll: 4, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Maya Das', class: 'Class 1', roll: 5, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Arif Hossain', class: 'Class 1', roll: 6, section: 'B', date: '2024-12-30', attendance: 'late' },
    { name: 'Shaila Begum', class: 'Class 1', roll: 7, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Jamal Uddin', class: 'Class 1', roll: 8, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Tariq Rahman', class: 'Class 1', roll: 9, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Fatema Khatun', class: 'Class 1', roll: 10, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Nashit Ahmed', class: 'Class 1', roll: 11, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Rasheda Sultana', class: 'Class 1', roll: 12, section: 'B', date: '2024-12-30', attendance: 'late' },
    { name: 'Musa Khan', class: 'Class 1', roll: 13, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Kajal Saha', class: 'Class 1', roll: 14, section: 'A', date: '2024-12-30', attendance: 'absent' },
    { name: 'Afsana Rahman', class: 'Class 1', roll: 15, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Sayeed Islam', class: 'Class 1', roll: 16, section: 'B', date: '2024-12-30', attendance: 'late' },
    { name: 'Samina Begum', class: 'Class 1', roll: 17, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Junaid Mollah', class: 'Class 1', roll: 18, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Sana Jahan', class: 'Class 1', roll: 19, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Anwar Hossain', class: 'Class 1', roll: 20, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Tanvir Hossain', class: 'Class 1', roll: 21, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Bashir Ahmed', class: 'Class 1', roll: 22, section: 'A', date: '2024-12-30', attendance: 'late' },
    { name: 'Nilima Rahman', class: 'Class 1', roll: 23, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Khalid Islam', class: 'Class 1', roll: 24, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Hasan Chowdhury', class: 'Class 1', roll: 25, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Rashida Begum', class: 'Class 1', roll: 26, section: 'C', date: '2024-12-30', attendance: 'absent' },
    { name: 'Siddiqur Rahman', class: 'Class 1', roll: 27, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Fahmida Islam', class: 'Class 1', roll: 28, section: 'D', date: '2024-12-30', attendance: 'late' },
    { name: 'Shahidul Alam', class: 'Class 1', roll: 29, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Rabia Sultana', class: 'Class 1', roll: 30, section: 'A', date: '2024-12-30', attendance: 'absent' },
    { name: 'Jabed Rahman', class: 'Class 1', roll: 31, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Liza Akter', class: 'Class 1', roll: 32, section: 'B', date: '2024-12-30', attendance: 'late' },



    { name: 'Abdul Karim', class: 'Class 2', roll: 1, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Zara Alam', class: 'Class 2', roll: 2, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Samiul Islam', class: 'Class 2', roll: 3, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Shilpa Saha', class: 'Class 2', roll: 4, section: 'B', date: '2024-12-30', attendance: 'late' },
    { name: 'Javed Mollah', class: 'Class 2', roll: 5, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Rima Chowdhury', class: 'Class 2', roll: 6, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Asif Hossain', class: 'Class 2', roll: 7, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Mahiya Islam', class: 'Class 2', roll: 8, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Fahim Ahmed', class: 'Class 2', roll: 9, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Shahnaz Begum', class: 'Class 2', roll: 10, section: 'A', date: '2024-12-30', attendance: 'late' },
    { name: 'Nafisa Akter', class: 'Class 2', roll: 11, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Tariq Rahman', class: 'Class 2', roll: 12, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Sharif Uddin', class: 'Class 2', roll: 13, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Noorjahan Sultana', class: 'Class 2', roll: 14, section: 'C', date: '2024-12-30', attendance: 'late' },
    { name: 'Saima Jahan', class: 'Class 2', roll: 15, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Mushfiqur Rahman', class: 'Class 2', roll: 16, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Karim Chowdhury', class: 'Class 2', roll: 17, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Sabrina Akter', class: 'Class 2', roll: 18, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Rahat Ali', class: 'Class 2', roll: 19, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Ruksana Begum', class: 'Class 2', roll: 20, section: 'B', date: '2024-12-30', attendance: 'absent' },
    { name: 'Khaled Hossain', class: 'Class 2', roll: 21, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Fatema Khatun', class: 'Class 2', roll: 22, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Mushfiqur Islam', class: 'Class 2', roll: 23, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Nusrat Jahan', class: 'Class 2', roll: 24, section: 'D', date: '2024-12-30', attendance: 'late' },
    { name: 'Abida Rahman', class: 'Class 2', roll: 25, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Junaid Chowdhury', class: 'Class 2', roll: 26, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Sultana Begum', class: 'Class 2', roll: 27, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Shuhel Islam', class: 'Class 2', roll: 28, section: 'B', date: '2024-12-30', attendance: 'late' },
    { name: 'Zakir Hossain', class: 'Class 2', roll: 29, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Shamima Akter', class: 'Class 2', roll: 30, section: 'C', date: '2024-12-30', attendance: 'absent' },
    { name: 'Rafiq Ahmed', class: 'Class 2', roll: 31, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Tania Begum', class: 'Class 2', roll: 32, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Moumita Saha', class: 'Class 2', roll: 33, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Shahida Begum', class: 'Class 2', roll: 34, section: 'A', date: '2024-12-30', attendance: 'absent' },
    { name: 'Suman Hossain', class: 'Class 2', roll: 35, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Asma Sultana', class: 'Class 2', roll: 36, section: 'B', date: '2024-12-30', attendance: 'late' },
    { name: 'Tahmina Sultana', class: 'Class 2', roll: 37, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Rakibul Islam', class: 'Class 2', roll: 38, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Shahriar Khan', class: 'Class 2', roll: 39, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Mahbuba Akter', class: 'Class 2', roll: 40, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Anwar Hossain', class: 'Class 2', roll: 41, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Safiur Rahman', class: 'Class 2', roll: 42, section: 'A', date: '2024-12-30', attendance: 'late' },
    { name: 'Momena Sultana', class: 'Class 2', roll: 43, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Adil Khan', class: 'Class 2', roll: 44, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Momena Begum', class: 'Class 2', roll: 45, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Iqbal Hossain', class: 'Class 2', roll: 46, section: 'C', date: '2024-12-30', attendance: 'absent' },
    { name: 'Shahina Akter', class: 'Class 2', roll: 47, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Hasan Mahmud', class: 'Class 2', roll: 48, section: 'D', date: '2024-12-30', attendance: 'late' },
    { name: 'Naila Begum', class: 'Class 2', roll: 49, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Rayan Saha', class: 'Class 2', roll: 50, section: 'A', date: '2024-12-30', attendance: 'present' },


    { name: 'Rafiul Islam', class: 'Class 3', roll: 1, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Moushumi Saha', class: 'Class 3', roll: 2, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Sakib Chowdhury', class: 'Class 3', roll: 3, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Farah Akter', class: 'Class 3', roll: 4, section: 'B', date: '2024-12-30', attendance: 'late' },
    { name: 'Ishrat Jahan', class: 'Class 3', roll: 5, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Imran Rahman', class: 'Class 3', roll: 6, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Asma Banu', class: 'Class 3', roll: 7, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Zubair Hossain', class: 'Class 3', roll: 8, section: 'D', date: '2024-12-30', attendance: 'absent' },
    { name: 'Mohiuddin Mollah', class: 'Class 3', roll: 9, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Sara Sultana', class: 'Class 3', roll: 10, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Shahinur Rahman', class: 'Class 3', roll: 11, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Taslima Begum', class: 'Class 3', roll: 12, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Adnan Chowdhury', class: 'Class 3', roll: 13, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Marium Khan', class: 'Class 3', roll: 14, section: 'C', date: '2024-12-30', attendance: 'late' },
    { name: 'Shamsul Alam', class: 'Class 3', roll: 15, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Shamima Rahman', class: 'Class 3', roll: 16, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Nusrat Sultana', class: 'Class 3', roll: 17, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Rashed Chowdhury', class: 'Class 3', roll: 18, section: 'A', date: '2024-12-30', attendance: 'late' },
    { name: 'Mohammad Ali', class: 'Class 3', roll: 19, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Saira Begum', class: 'Class 3', roll: 20, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Rima Rahman', class: 'Class 3', roll: 21, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Shahina Khan', class: 'Class 3', roll: 22, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Ariful Islam', class: 'Class 3', roll: 23, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Shahana Begum', class: 'Class 3', roll: 24, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Sharmin Sultana', class: 'Class 3', roll: 25, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Ahsan Khan', class: 'Class 3', roll: 26, section: 'A', date: '2024-12-30', attendance: 'absent' },
    { name: 'Rishad Rahman', class: 'Class 3', roll: 27, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Fatima Akter', class: 'Class 3', roll: 28, section: 'B', date: '2024-12-30', attendance: 'late' },
    { name: 'Tareq Mollah', class: 'Class 3', roll: 29, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Liza Sultana', class: 'Class 3', roll: 30, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Yasir Chowdhury', class: 'Class 3', roll: 31, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Marium Akter', class: 'Class 3', roll: 32, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Saad Rahman', class: 'Class 3', roll: 33, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Mahmud Alam', class: 'Class 3', roll: 34, section: 'A', date: '2024-12-30', attendance: 'absent' },
    { name: 'Aliza Khan', class: 'Class 3', roll: 35, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Samiha Rahman', class: 'Class 3', roll: 36, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Fahim Chowdhury', class: 'Class 3', roll: 37, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Sarina Begum', class: 'Class 3', roll: 38, section: 'C', date: '2024-12-30', attendance: 'absent' },
    { name: 'Nabil Hossain', class: 'Class 3', roll: 39, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Junaid Alam', class: 'Class 3', roll: 40, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Karim Uddin', class: 'Class 3', roll: 41, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Lubna Rahman', class: 'Class 3', roll: 42, section: 'A', date: '2024-12-30', attendance: 'absent' },
    { name: 'Husna Sultana', class: 'Class 3', roll: 43, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Shahinur Islam', class: 'Class 3', roll: 44, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Tawfiq Rahman', class: 'Class 3', roll: 45, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Suhana Chowdhury', class: 'Class 3', roll: 46, section: 'C', date: '2024-12-30', attendance: 'absent' },
    { name: 'Aminur Rahman', class: 'Class 3', roll: 47, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Dilara Sultana', class: 'Class 3', roll: 48, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Asif Ahmed', class: 'Class 3', roll: 49, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Taslima Chowdhury', class: 'Class 3', roll: 50, section: 'A', date: '2024-12-30', attendance: 'absent' },
    { name: 'Masum Ahmed', class: 'Class 3', roll: 51, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Ranya Begum', class: 'Class 3', roll: 52, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Sakina Akter', class: 'Class 3', roll: 53, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Zahid Khan', class: 'Class 3', roll: 54, section: 'C', date: '2024-12-30', attendance: 'absent' },
    { name: 'Imran Chowdhury', class: 'Class 3', roll: 55, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Sabrina Akter', class: 'Class 3', roll: 56, section: 'D', date: '2024-12-30', attendance: 'late' },



    { name: 'Shakil Rahman', class: 'Class 4', roll: 1, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Ayesha Begum', class: 'Class 4', roll: 2, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Tanveer Alam', class: 'Class 4', roll: 3, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Munni Sultana', class: 'Class 4', roll: 4, section: 'B', date: '2024-12-30', attendance: 'late' },
    { name: 'Zakir Hossain', class: 'Class 4', roll: 5, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Rumana Akter', class: 'Class 4', roll: 6, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Samira Rahman', class: 'Class 4', roll: 7, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Mumtaz Ahmed', class: 'Class 4', roll: 8, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Rifat Chowdhury', class: 'Class 4', roll: 9, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Shumon Ahmed', class: 'Class 4', roll: 10, section: 'A', date: '2024-12-30', attendance: 'late' },
    { name: 'Mohiuddin Rahman', class: 'Class 4', roll: 11, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Madhurima Saha', class: 'Class 4', roll: 12, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Jannat Sultana', class: 'Class 4', roll: 13, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Shahzaib Khan', class: 'Class 4', roll: 14, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Nadia Akter', class: 'Class 4', roll: 15, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Shahidul Alam', class: 'Class 4', roll: 16, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Tanisha Rahman', class: 'Class 4', roll: 17, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Arifur Rahman', class: 'Class 4', roll: 18, section: 'A', date: '2024-12-30', attendance: 'late' },
    { name: 'Lamia Sultana', class: 'Class 4', roll: 19, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Ahmed Jamil', class: 'Class 4', roll: 20, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Nusrat Jahan', class: 'Class 4', roll: 21, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Jubair Alam', class: 'Class 4', roll: 22, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Rahul Hossain', class: 'Class 4', roll: 23, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Mounira Akter', class: 'Class 4', roll: 24, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Shamina Sultana', class: 'Class 4', roll: 25, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Ahsanul Rahman', class: 'Class 4', roll: 26, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Samiul Islam', class: 'Class 4', roll: 27, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Shamsuddin Chowdhury', class: 'Class 4', roll: 28, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Nashit Rahman', class: 'Class 4', roll: 29, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Riya Sultana', class: 'Class 4', roll: 30, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Rafiq Hossain', class: 'Class 4', roll: 31, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Saima Akter', class: 'Class 4', roll: 32, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Fahmida Begum', class: 'Class 4', roll: 33, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Kazi Shafiq', class: 'Class 4', roll: 34, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Nashit Rahman', class: 'Class 4', roll: 35, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Parveen Akter', class: 'Class 4', roll: 36, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Shadman Rahman', class: 'Class 4', roll: 37, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Samar Alam', class: 'Class 4', roll: 38, section: 'C', date: '2024-12-30', attendance: 'late' },
    { name: 'Tariq Rahman', class: 'Class 4', roll: 39, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Shahjahan Sultana', class: 'Class 4', roll: 40, section: 'D', date: '2024-12-30', attendance: 'absent' },
    { name: 'Farzana Begum', class: 'Class 4', roll: 41, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Aminul Islam', class: 'Class 4', roll: 42, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Hina Chowdhury', class: 'Class 4', roll: 43, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Fahim Sultana', class: 'Class 4', roll: 44, section: 'B', date: '2024-12-30', attendance: 'absent' },
    { name: 'Hassan Rahman', class: 'Class 4', roll: 45, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Monira Begum', class: 'Class 4', roll: 46, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Muna Akter', class: 'Class 4', roll: 47, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Yasir Alam', class: 'Class 4', roll: 48, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Riaz Sultana', class: 'Class 4', roll: 49, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Asma Rahman', class: 'Class 4', roll: 50, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Sharmin Hossain', class: 'Class 4', roll: 51, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Fahad Mollah', class: 'Class 4', roll: 52, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Tanjina Begum', class: 'Class 4', roll: 53, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Suman Islam', class: 'Class 4', roll: 54, section: 'C', date: '2024-12-30', attendance: 'late' },
    { name: 'Mushfiq Rahman', class: 'Class 4', roll: 55, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Arshad Rahman', class: 'Class 4', roll: 56, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Shahina Akter', class: 'Class 4', roll: 57, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Masud Khan', class: 'Class 4', roll: 58, section: 'A', date: '2024-12-30', attendance: 'late' },
    { name: 'Rumana Rahman', class: 'Class 4', roll: 59, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Sadiq Alam', class: 'Class 4', roll: 60, section: 'B', date: '2024-12-30', attendance: 'present' },



    { name: 'Tanisha Akter', class: 'Class 5', roll: 1, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Fariha Rahman', class: 'Class 5', roll: 2, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Jahidul Islam', class: 'Class 5', roll: 3, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Rahima Sultana', class: 'Class 5', roll: 4, section: 'B', date: '2024-12-30', attendance: 'late' },
    { name: 'Iqbal Hossain', class: 'Class 5', roll: 5, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Raihan Chowdhury', class: 'Class 5', roll: 6, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Mushfiqur Rahman', class: 'Class 5', roll: 7, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Hina Sultana', class: 'Class 5', roll: 8, section: 'D', date: '2024-12-30', attendance: 'absent' },
    { name: 'Aminul Islam', class: 'Class 5', roll: 9, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Tanvir Alam', class: 'Class 5', roll: 10, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Shahina Begum', class: 'Class 5', roll: 11, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Fahim Chowdhury', class: 'Class 5', roll: 12, section: 'B', date: '2024-12-30', attendance: 'absent' },
    { name: 'Sadia Rahman', class: 'Class 5', roll: 13, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Shafique Ahmed', class: 'Class 5', roll: 14, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Tariq Rahman', class: 'Class 5', roll: 15, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Sara Sultana', class: 'Class 5', roll: 16, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Kazi Farhan', class: 'Class 5', roll: 17, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Moureen Begum', class: 'Class 5', roll: 18, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Imran Khan', class: 'Class 5', roll: 19, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Amina Rahman', class: 'Class 5', roll: 20, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Jubair Chowdhury', class: 'Class 5', roll: 21, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Soma Akter', class: 'Class 5', roll: 22, section: 'C', date: '2024-12-30', attendance: 'late' },
    { name: 'Farzana Begum', class: 'Class 5', roll: 23, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Hossain Mollah', class: 'Class 5', roll: 24, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Shahidul Rahman', class: 'Class 5', roll: 25, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Lamia Chowdhury', class: 'Class 5', roll: 26, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Shahzaib Alam', class: 'Class 5', roll: 27, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Dilara Sultana', class: 'Class 5', roll: 28, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Shamima Akter', class: 'Class 5', roll: 29, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Rafat Hossain', class: 'Class 5', roll: 30, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Arif Hossain', class: 'Class 5', roll: 31, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Rokeya Begum', class: 'Class 5', roll: 32, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Hassan Alam', class: 'Class 5', roll: 33, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Sabrina Rahman', class: 'Class 5', roll: 34, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Al Amin', class: 'Class 5', roll: 35, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Shabana Akter', class: 'Class 5', roll: 36, section: 'B', date: '2024-12-30', attendance: 'absent' },
    { name: 'Samiul Islam', class: 'Class 5', roll: 37, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Madhumita Saha', class: 'Class 5', roll: 38, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Shamim Ahmed', class: 'Class 5', roll: 39, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Fariha Sultana', class: 'Class 5', roll: 40, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Rumi Rahman', class: 'Class 5', roll: 41, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Maksud Chowdhury', class: 'Class 5', roll: 42, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Shaheda Akter', class: 'Class 5', roll: 43, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Kawsar Rahman', class: 'Class 5', roll: 44, section: 'B', date: '2024-12-30', attendance: 'absent' },
    { name: 'Sadia Chowdhury', class: 'Class 5', roll: 45, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Sohail Alam', class: 'Class 5', roll: 46, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Salma Begum', class: 'Class 5', roll: 47, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Yasir Rahman', class: 'Class 5', roll: 48, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Hira Sultana', class: 'Class 5', roll: 49, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Shamim Chowdhury', class: 'Class 5', roll: 50, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Marta Saha', class: 'Class 5', roll: 51, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Rahman Munir', class: 'Class 5', roll: 52, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Aklima Begum', class: 'Class 5', roll: 53, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Zakia Chowdhury', class: 'Class 5', roll: 54, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Shadman Rahman', class: 'Class 5', roll: 55, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Shakira Islam', class: 'Class 5', roll: 56, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Arif Akter', class: 'Class 5', roll: 57, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Rizwan Rahman', class: 'Class 5', roll: 58, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Riya Begum', class: 'Class 5', roll: 59, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Khaleda Sultana', class: 'Class 5', roll: 60, section: 'B', date: '2024-12-30', attendance: 'present' },



    { name: 'Ahsanur Rahman', class: 'Class 6', roll: 1, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Tasmina Rahman', class: 'Class 6', roll: 2, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Shamim Hossain', class: 'Class 6', roll: 3, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Laila Sultana', class: 'Class 6', roll: 4, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Tariq Islam', class: 'Class 6', roll: 5, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Kawsar Rahman', class: 'Class 6', roll: 6, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Jannat Akter', class: 'Class 6', roll: 7, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Sohail Chowdhury', class: 'Class 6', roll: 8, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Fariha Rahman', class: 'Class 6', roll: 9, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Raihan Akter', class: 'Class 6', roll: 10, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Hasina Begum', class: 'Class 6', roll: 11, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Zakir Hossain', class: 'Class 6', roll: 12, section: 'B', date: '2024-12-30', attendance: 'absent' },
    { name: 'Maha Rahman', class: 'Class 6', roll: 13, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Samiul Chowdhury', class: 'Class 6', roll: 14, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Shahina Akter', class: 'Class 6', roll: 15, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Sadiya Rahman', class: 'Class 6', roll: 16, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Mushfiq Rahman', class: 'Class 6', roll: 17, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Aminul Islam', class: 'Class 6', roll: 18, section: 'A', date: '2024-12-30', attendance: 'late' },
    { name: 'Khaled Sultana', class: 'Class 6', roll: 19, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Shahjalal Rahman', class: 'Class 6', roll: 20, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Ruma Begum', class: 'Class 6', roll: 21, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Sahil Alam', class: 'Class 6', roll: 22, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Salma Rahman', class: 'Class 6', roll: 23, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Shahed Alam', class: 'Class 6', roll: 24, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Rabiya Sultana', class: 'Class 6', roll: 25, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Mahbubur Rahman', class: 'Class 6', roll: 26, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Tanjina Begum', class: 'Class 6', roll: 27, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Imran Chowdhury', class: 'Class 6', roll: 28, section: 'B', date: '2024-12-30', attendance: 'absent' },
    { name: 'Sadia Begum', class: 'Class 6', roll: 29, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Nazma Begum', class: 'Class 6', roll: 30, section: 'C', date: '2024-12-30', attendance: 'late' },
    { name: 'Razia Akter', class: 'Class 6', roll: 31, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Ahsan Ahmed', class: 'Class 6', roll: 32, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Tanveer Hossain', class: 'Class 6', roll: 33, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Riyad Akter', class: 'Class 6', roll: 34, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Kashfia Sultana', class: 'Class 6', roll: 35, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Imtiaz Rahman', class: 'Class 6', roll: 36, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Mushfiqur Rahman', class: 'Class 6', roll: 37, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Shaikh Tanveer', class: 'Class 6', roll: 38, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Fariha Sultana', class: 'Class 6', roll: 39, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Sharif Rahman', class: 'Class 6', roll: 40, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Mizanur Rahman', class: 'Class 6', roll: 41, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Sufian Chowdhury', class: 'Class 6', roll: 42, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Shaila Begum', class: 'Class 6', roll: 43, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Irfan Alam', class: 'Class 6', roll: 44, section: 'B', date: '2024-12-30', attendance: 'absent' },
    { name: 'Raziya Sultana', class: 'Class 6', roll: 45, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Nashit Sultana', class: 'Class 6', roll: 46, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Nadim Rahman', class: 'Class 6', roll: 47, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Shama Begum', class: 'Class 6', roll: 48, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Aminah Sultana', class: 'Class 6', roll: 49, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Fazlur Rahman', class: 'Class 6', roll: 50, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Nabila Rahman', class: 'Class 6', roll: 51, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Omar Faruk', class: 'Class 6', roll: 52, section: 'B', date: '2024-12-30', attendance: 'absent' },
    { name: 'Jebin Sultana', class: 'Class 6', roll: 53, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Feroze Ahmed', class: 'Class 6', roll: 54, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Mahi Rahman', class: 'Class 6', roll: 55, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Saddam Hossain', class: 'Class 6', roll: 56, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Saima Begum', class: 'Class 6', roll: 57, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Kawsar Islam', class: 'Class 6', roll: 58, section: 'A', date: '2024-12-30', attendance: 'late' },
    { name: 'Almas Chowdhury', class: 'Class 6', roll: 59, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Mannan Rahman', class: 'Class 6', roll: 60, section: 'B', date: '2024-12-30', attendance: 'present' },



    { name: 'Abdullah Al Mamun', class: 'Class 7', roll: 1, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Shilpi Das', class: 'Class 7', roll: 2, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Zubair Hossain', class: 'Class 7', roll: 3, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Rima Sultana', class: 'Class 7', roll: 4, section: 'B', date: '2024-12-30', attendance: 'late' },
    { name: 'Sohail Khan', class: 'Class 7', roll: 5, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Amena Begum', class: 'Class 7', roll: 6, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Rashedul Islam', class: 'Class 7', roll: 7, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Mouri Akter', class: 'Class 7', roll: 8, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Shahina Rani', class: 'Class 7', roll: 9, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Rafiq Islam', class: 'Class 7', roll: 10, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Imran Chowdhury', class: 'Class 7', roll: 11, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Shaila Rahman', class: 'Class 7', roll: 12, section: 'B', date: '2024-12-30', attendance: 'absent' },
    { name: 'Fahim Hossain', class: 'Class 7', roll: 13, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Aminul Islam', class: 'Class 7', roll: 14, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Khaleda Akter', class: 'Class 7', roll: 15, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Shihab Chowdhury', class: 'Class 7', roll: 16, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Rubina Begum', class: 'Class 7', roll: 17, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Abir Rahman', class: 'Class 7', roll: 18, section: 'A', date: '2024-12-30', attendance: 'late' },
    { name: 'Tariq Rahman', class: 'Class 7', roll: 19, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Fariah Begum', class: 'Class 7', roll: 20, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Mushfiqur Rahman', class: 'Class 7', roll: 21, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Shariar Akter', class: 'Class 7', roll: 22, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Samia Chowdhury', class: 'Class 7', roll: 23, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Shahed Alam', class: 'Class 7', roll: 24, section: 'D', date: '2024-12-30', attendance: 'absent' },
    { name: 'Sohana Rani', class: 'Class 7', roll: 25, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Raihan Hossain', class: 'Class 7', roll: 26, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Farzana Rahman', class: 'Class 7', roll: 27, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Bipul Roy', class: 'Class 7', roll: 28, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Riya Islam', class: 'Class 7', roll: 29, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Rezaul Karim', class: 'Class 7', roll: 30, section: 'C', date: '2024-12-30', attendance: 'late' },
    { name: 'Misti Akter', class: 'Class 7', roll: 31, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Jannat Akter', class: 'Class 7', roll: 32, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Saima Sultana', class: 'Class 7', roll: 33, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Nashit Chowdhury', class: 'Class 7', roll: 34, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Rahela Begum', class: 'Class 7', roll: 35, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Imran Hossain', class: 'Class 7', roll: 36, section: 'B', date: '2024-12-30', attendance: 'absent' },
    { name: 'Jahid Hasan', class: 'Class 7', roll: 37, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Moyna Rani', class: 'Class 7', roll: 38, section: 'C', date: '2024-12-30', attendance: 'late' },
    { name: 'Sadia Begum', class: 'Class 7', roll: 39, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Arman Chowdhury', class: 'Class 7', roll: 40, section: 'D', date: '2024-12-30', attendance: 'absent' },
    { name: 'Tanvi Hossain', class: 'Class 7', roll: 41, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Mubin Rahman', class: 'Class 7', roll: 42, section: 'A', date: '2024-12-30', attendance: 'late' },
    { name: 'Maimuna Begum', class: 'Class 7', roll: 43, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Tanvir Islam', class: 'Class 7', roll: 44, section: 'B', date: '2024-12-30', attendance: 'absent' },
    { name: 'Sadman Chowdhury', class: 'Class 7', roll: 45, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Sabrin Sultana', class: 'Class 7', roll: 46, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Rubel Rahman', class: 'Class 7', roll: 47, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Nadia Begum', class: 'Class 7', roll: 48, section: 'D', date: '2024-12-30', attendance: 'absent' },
    { name: 'Shahinur Rahman', class: 'Class 7', roll: 49, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Ameer Chowdhury', class: 'Class 7', roll: 50, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Tanzila Begum', class: 'Class 7', roll: 51, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Arman Rahman', class: 'Class 7', roll: 52, section: 'B', date: '2024-12-30', attendance: 'absent' },
    { name: 'Maruf Hossain', class: 'Class 7', roll: 53, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Fahima Rahman', class: 'Class 7', roll: 54, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Sana Chowdhury', class: 'Class 7', roll: 55, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Nashit Alam', class: 'Class 7', roll: 56, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Akter Sultana', class: 'Class 7', roll: 57, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Rahman Chowdhury', class: 'Class 7', roll: 58, section: 'A', date: '2024-12-30', attendance: 'late' },
    { name: 'Munir Hossain', class: 'Class 7', roll: 59, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Nafisa Akter', class: 'Class 7', roll: 60, section: 'B', date: '2024-12-30', attendance: 'present' },



    { name: 'Samiul Islam', class: 'Class 8', roll: 1, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Rifat Hossain', class: 'Class 8', roll: 2, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Shihab Rahman', class: 'Class 8', roll: 3, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Tania Akter', class: 'Class 8', roll: 4, section: 'B', date: '2024-12-30', attendance: 'late' },
    { name: 'Foysal Chowdhury', class: 'Class 8', roll: 5, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Papia Sultana', class: 'Class 8', roll: 6, section: 'C', date: '2024-12-30', attendance: 'absent' },
    { name: 'Junaid Akter', class: 'Class 8', roll: 7, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Noor Hossain', class: 'Class 8', roll: 8, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Rohit Saha', class: 'Class 8', roll: 9, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Mithila Rani', class: 'Class 8', roll: 10, section: 'A', date: '2024-12-30', attendance: 'late' },
    { name: 'Nashit Alam', class: 'Class 8', roll: 11, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Aisha Begum', class: 'Class 8', roll: 12, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Hasan Mahmud', class: 'Class 8', roll: 13, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Sumaiya Sultana', class: 'Class 8', roll: 14, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Sumiya Akter', class: 'Class 8', roll: 15, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Sohanur Rahman', class: 'Class 8', roll: 16, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Mahi Chowdhury', class: 'Class 8', roll: 17, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Shamina Begum', class: 'Class 8', roll: 18, section: 'A', date: '2024-12-30', attendance: 'late' },
    { name: 'Rafiq Chowdhury', class: 'Class 8', roll: 19, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Salma Akter', class: 'Class 8', roll: 20, section: 'B', date: '2024-12-30', attendance: 'abspresentent' },
    { name: 'Mohammad Alam', class: 'Class 8', roll: 21, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Farhana Begum', class: 'Class 8', roll: 22, section: 'C', date: '2024-12-30', attendance: 'late' },
    { name: 'Fahim Islam', class: 'Class 8', roll: 23, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Tariq Rahman', class: 'Class 8', roll: 24, section: 'D', date: '2024-12-30', attendance: 'absent' },
    { name: 'Sadia Alam', class: 'Class 8', roll: 25, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Mojibur Rahman', class: 'Class 8', roll: 26, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Dipa Sultana', class: 'Class 8', roll: 27, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Ahsan Rafiq', class: 'Class 8', roll: 28, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Sohag Rahman', class: 'Class 8', roll: 29, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Mim Rani', class: 'Class 8', roll: 30, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Tanvir Rahman', class: 'Class 8', roll: 31, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Riaz Alam', class: 'Class 8', roll: 32, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Mahi Rahman', class: 'Class 8', roll: 33, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Fatima Akter', class: 'Class 8', roll: 34, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Nazia Sultana', class: 'Class 8', roll: 35, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Shameem Rahman', class: 'Class 8', roll: 36, section: 'B', date: '2024-12-30', attendance: 'absent' },
    { name: 'Rifatul Islam', class: 'Class 8', roll: 37, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Bipasha Chowdhury', class: 'Class 8', roll: 38, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Aminur Rahman', class: 'Class 8', roll: 39, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Dewan Hossain', class: 'Class 8', roll: 40, section: 'D', date: '2024-12-30', attendance: 'absent' },
    { name: 'Sabiha Akter', class: 'Class 8', roll: 41, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Sazzad Hossain', class: 'Class 8', roll: 42, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Rasel Rahman', class: 'Class 8', roll: 43, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Nashit Sultana', class: 'Class 8', roll: 44, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Fazlul Karim', class: 'Class 8', roll: 45, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Rima Chowdhury', class: 'Class 8', roll: 46, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Shahed Alam', class: 'Class 8', roll: 47, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Mubin Sultana', class: 'Class 8', roll: 48, section: 'D', date: '2024-12-30', attendance: 'absent' },
    { name: 'Risha Rahman', class: 'Class 8', roll: 49, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Rehena Begum', class: 'Class 8', roll: 50, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Zubair Rahman', class: 'Class 8', roll: 51, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Nasrin Akter', class: 'Class 8', roll: 52, section: 'B', date: '2024-12-30', attendance: 'absent' },
    { name: 'Shamim Chowdhury', class: 'Class 8', roll: 53, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Fayza Rani', class: 'Class 8', roll: 54, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Nafisa Sultana', class: 'Class 8', roll: 55, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Sohail Rahman', class: 'Class 8', roll: 56, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Munna Rafiq', class: 'Class 8', roll: 57, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Khaleda Akter', class: 'Class 8', roll: 58, section: 'A', date: '2024-12-30', attendance: 'late' },
    { name: 'Md. Abdullah', class: 'Class 8', roll: 59, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Bithi Sultana', class: 'Class 8', roll: 60, section: 'B', date: '2024-12-30', attendance: 'present' },



    { name: 'Shihab Islam', class: 'Class 9', roll: 1, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Tania Rahman', class: 'Class 9', roll: 2, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Shifat Alam', class: 'Class 9', roll: 3, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Fahim Chowdhury', class: 'Class 9', roll: 4, section: 'B', date: '2024-12-30', attendance: 'late' },
    { name: 'Fatema Sultana', class: 'Class 9', roll: 5, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Saniul Rahman', class: 'Class 9', roll: 6, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Meherin Akter', class: 'Class 9', roll: 7, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Sharmin Sultana', class: 'Class 9', roll: 8, section: 'D', date: '2024-12-30', attendance: 'absent' },
    { name: 'Rakibul Islam', class: 'Class 9', roll: 9, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Moyna Akter', class: 'Class 9', roll: 10, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Mithila Rani', class: 'Class 9', roll: 11, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Rahil Chowdhury', class: 'Class 9', roll: 12, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Sabeen Akter', class: 'Class 9', roll: 13, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Sujon Hossain', class: 'Class 9', roll: 14, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Shamsul Rahman', class: 'Class 9', roll: 15, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Raheel Chowdhury', class: 'Class 9', roll: 16, section: 'D', date: '2024-12-30', attendance: 'absent' },
    { name: 'Sina Rani', class: 'Class 9', roll: 17, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Rafique Rahman', class: 'Class 9', roll: 18, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Sumaiya Chowdhury', class: 'Class 9', roll: 19, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Rashid Rahman', class: 'Class 9', roll: 20, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Aisha Sultana', class: 'Class 9', roll: 21, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Sharif Hossain', class: 'Class 9', roll: 22, section: 'C', date: '2024-12-30', attendance: 'late' },
    { name: 'Anika Akter', class: 'Class 9', roll: 23, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Sharif Rahman', class: 'Class 9', roll: 24, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Zahid Rahman', class: 'Class 9', roll: 25, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Mithun Chowdhury', class: 'Class 9', roll: 26, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Tariq Sultana', class: 'Class 9', roll: 27, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Mokhlesur Rahman', class: 'Class 9', roll: 28, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Rafiul Alam', class: 'Class 9', roll: 29, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Mitali Hossain', class: 'Class 9', roll: 30, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Tarin Chowdhury', class: 'Class 9', roll: 31, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Foysal Alam', class: 'Class 9', roll: 32, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Asif Chowdhury', class: 'Class 9', roll: 33, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Mim Rani', class: 'Class 9', roll: 34, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Khaleda Rahman', class: 'Class 9', roll: 35, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Mizanur Rahman', class: 'Class 9', roll: 36, section: 'B', date: '2024-12-30', attendance: 'absent' },
    { name: 'Ruba Sultana', class: 'Class 9', roll: 37, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Foysal Sultana', class: 'Class 9', roll: 38, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Rina Rahman', class: 'Class 9', roll: 39, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Saurabh Chowdhury', class: 'Class 9', roll: 40, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Mehedi Sultana', class: 'Class 9', roll: 41, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Rifat Rahman', class: 'Class 9', roll: 42, section: 'A', date: '2024-12-30', attendance: 'late' },
    { name: 'Saniul Islam', class: 'Class 9', roll: 43, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Salma Rahman', class: 'Class 9', roll: 44, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Alif Rahman', class: 'Class 9', roll: 45, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Bipasha Rani', class: 'Class 9', roll: 46, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Kamrul Islam', class: 'Class 9', roll: 47, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Rishad Sultana', class: 'Class 9', roll: 48, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Samiul Rahman', class: 'Class 9', roll: 49, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Nashit Chowdhury', class: 'Class 9', roll: 50, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Arif Sultana', class: 'Class 9', roll: 51, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Rabiul Rahman', class: 'Class 9', roll: 52, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Shahla Akter', class: 'Class 9', roll: 53, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Rasel Sultana', class: 'Class 9', roll: 54, section: 'C', date: '2024-12-30', attendance: 'late' },
    { name: 'Farida Sultana', class: 'Class 9', roll: 55, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Bashir Rahman', class: 'Class 9', roll: 56, section: 'D', date: '2024-12-30', attendance: 'absent' },
    { name: 'Anis Rahman', class: 'Class 9', roll: 57, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Salim Sultana', class: 'Class 9', roll: 58, section: 'A', date: '2024-12-30', attendance: 'late' },
    { name: 'Fahim Chowdhury', class: 'Class 9', roll: 59, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Sajib Alam', class: 'Class 9', roll: 60, section: 'B', date: '2024-12-30', attendance: 'present' },



    { name: 'Samiul Islam', class: 'Class 10', roll: 1, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Nashit Rahman', class: 'Class 10', roll: 2, section: 'A', date: '2024-12-30', attendance: 'absent' },
    { name: 'Rasha Akter', class: 'Class 10', roll: 3, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Sharmin Sultana', class: 'Class 10', roll: 4, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Mithila Rahman', class: 'Class 10', roll: 5, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Aminul Islam', class: 'Class 10', roll: 6, section: 'C', date: '2024-12-30', attendance: 'absent' },
    { name: 'Zahid Akter', class: 'Class 10', roll: 7, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Fahim Chowdhury', class: 'Class 10', roll: 8, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Ruba Sultana', class: 'Class 10', roll: 9, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Jannat Akter', class: 'Class 10', roll: 10, section: 'A', date: '2024-12-30', attendance: 'late' },
    { name: 'Mehedi Rahman', class: 'Class 10', roll: 11, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Riyad Chowdhury', class: 'Class 10', roll: 12, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Raheel Sultana', class: 'Class 10', roll: 13, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Fatema Rahman', class: 'Class 10', roll: 14, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Sajid Rahman', class: 'Class 10', roll: 15, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Mizan Rahman', class: 'Class 10', roll: 16, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Arif Chowdhury', class: 'Class 10', roll: 17, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Rifat Rahman', class: 'Class 10', roll: 18, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Nafisa Akter', class: 'Class 10', roll: 19, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Foysal Rahman', class: 'Class 10', roll: 20, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Rasha Rahman', class: 'Class 10', roll: 21, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Shifa Chowdhury', class: 'Class 10', roll: 22, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Shahida Rahman', class: 'Class 10', roll: 23, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Tariq Chowdhury', class: 'Class 10', roll: 24, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Rina Sultana', class: 'Class 10', roll: 25, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Samiul Chowdhury', class: 'Class 10', roll: 26, section: 'A', date: '2024-12-30', attendance: 'late' },
    { name: 'Nasrin Akter', class: 'Class 10', roll: 27, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Foysal Alam', class: 'Class 10', roll: 28, section: 'B', date: '2024-12-30', attendance: 'absent' },
    { name: 'Rasid Rahman', class: 'Class 10', roll: 29, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Mumtaz Rani', class: 'Class 10', roll: 30, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Tariq Alam', class: 'Class 10', roll: 31, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Shahin Sultana', class: 'Class 10', roll: 32, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Rashed Rahman', class: 'Class 10', roll: 33, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Alif Akter', class: 'Class 10', roll: 34, section: 'A', date: '2024-12-30', attendance: 'late' },
    { name: 'Mohiuddin Chowdhury', class: 'Class 10', roll: 35, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Ishrat Sultana', class: 'Class 10', roll: 36, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Rukhsar Rahman', class: 'Class 10', roll: 37, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Mim Rahman', class: 'Class 10', roll: 38, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Sakib Rahman', class: 'Class 10', roll: 39, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Nabila Akter', class: 'Class 10', roll: 40, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Mahin Akter', class: 'Class 10', roll: 41, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Sarmila Rahman', class: 'Class 10', roll: 42, section: 'A', date: '2024-12-30', attendance: 'late' },
    { name: 'Mizan Rahman', class: 'Class 10', roll: 43, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Rafiq Sultana', class: 'Class 10', roll: 44, section: 'B', date: '2024-12-30', attendance: 'absent' },
    { name: 'Fayza Sultana', class: 'Class 10', roll: 45, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Shahina Chowdhury', class: 'Class 10', roll: 46, section: 'C', date: '2024-12-30', attendance: 'late' },
    { name: 'Hassan Rahman', class: 'Class 10', roll: 47, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Sultana Akter', class: 'Class 10', roll: 48, section: 'D', date: '2024-12-30', attendance: 'absent' },
    { name: 'Tamina Rahman', class: 'Class 10', roll: 49, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Riya Chowdhury', class: 'Class 10', roll: 50, section: 'A', date: '2024-12-30', attendance: 'late' },
    { name: 'Tanveer Sultana', class: 'Class 10', roll: 51, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Anika Chowdhury', class: 'Class 10', roll: 52, section: 'B', date: '2024-12-30', attendance: 'absent' },
    { name: 'Salma Rahman', class: 'Class 10', roll: 53, section: 'C', date: '2024-12-30', attendance: 'present' },
    { name: 'Sohail Sultana', class: 'Class 10', roll: 54, section: 'C', date: '2024-12-30', attendance: 'late' },
    { name: 'Anisur Rahman', class: 'Class 10', roll: 55, section: 'D', date: '2024-12-30', attendance: 'present' },
    { name: 'Sabina Rahman', class: 'Class 10', roll: 56, section: 'D', date: '2024-12-30', attendance: 'absent' },
    { name: 'Rahim Chowdhury', class: 'Class 10', roll: 57, section: 'A', date: '2024-12-30', attendance: 'present' },
    { name: 'Bithi Rahman', class: 'Class 10', roll: 58, section: 'A', date: '2024-12-30', attendance: 'late' },
    { name: 'Shafiul Rahman', class: 'Class 10', roll: 59, section: 'B', date: '2024-12-30', attendance: 'present' },
    { name: 'Jihan Chowdhury', class: 'Class 10', roll: 60, section: 'B', date: '2024-12-30', attendance: 'absent' },




  ];

  // Filtered attendance data based on selected class and date
  filteredAttendance = this.allAttendance.filter(
    (attendance) => attendance.class === this.selectedClass && attendance.date === this.selectedDate
  );

  // Method to select a class
  selectClass(event: Event) {
    const selectedValue = (event.target as HTMLSelectElement).value;
    this.selectedClass = selectedValue;
    this.filterResults();
  }

  // Filter attendance based on selected class and date
  filterResults() {
    this.filteredAttendance = this.allAttendance.filter(
      (attendance) =>
        attendance.class === this.selectedClass && attendance.date === this.selectedDate
    );
  }
}