export interface Student{
    id: number,
    f_name: String,
    l_name: String,
    fathersname: String,
    mothersname: String,
    dob: Date,
    gender: String,
    religion: String,
    nationality: String,
    fathersnumber: String,
    mothersnumber: String,
    studyingLevel: String,
    admissionclass: String,
    lastschool: String,
    presentaddress: String,
    permanentaddress: String,
    reference: String,
    photo: null,
    paymentType:String,
    payableAmount:Number,
    totalAmount:Number,
    terms:String
    paymentMethod:String
}